### PR TITLE
Fix fd leak in vsock.Dial in case of connect errors

### LINKED ISSUE #64: File descriptor leak in Dial function on Linux
Code in repo: https://github.com/linuxkit/virtsock/blob/f8cee7dfc7a3a337738ff3c1852fafe193a4f5d3/pkg/vsock/vsock_linux.go#L30-L47

The leak is on line 42, when we return from a function with error without closing a file descriptor.

### PR DESCRIPTION
**Pull request by xelez**
Fixes #64

Before commit when trying to connect in cycle with no valid endpoint:
```
$ lsof -p 874838 | grep AF_VSOCK
lsof: WARNING: can't stat() nsfs file system /run/docker/netns/default
      Output information may be incomplete.
servicevm 874838 xelez    9u     sock                0,9      0t0  8504215 protocol: AF_VSOCK
servicevm 874838 xelez   11u     sock                0,9      0t0  8504763 protocol: AF_VSOCK
servicevm 874838 xelez   12u     sock                0,9      0t0  8505726 protocol: AF_VSOCK
servicevm 874838 xelez   13u     sock                0,9      0t0  8504774 protocol: AF_VSOCK
servicevm 874838 xelez   14u     sock                0,9      0t0  8507619 protocol: AF_VSOCK
servicevm 874838 xelez   15u     sock                0,9      0t0  8500873 protocol: AF_VSOCK
servicevm 874838 xelez   16u     sock                0,9      0t0  8502193 protocol: AF_VSOCK
servicevm 874838 xelez   17u     sock                0,9      0t0  8507691 protocol: AF_VSOCK
servicevm 874838 xelez   18u     sock                0,9      0t0  8504845 protocol: AF_VSOCK
servicevm 874838 xelez   19u     sock                0,9      0t0  8510828 protocol: AF_VSOCK
```

After this patch no FD are leaking:
```
$ lsof -p 876844 | grep AF_VSOCK
lsof: WARNING: can't stat() nsfs file system /run/docker/netns/default
      Output information may be incomplete.
```

Signed-off-by: Alex Ankudinov <xelez0@gmail.com>

### CODE REVIEW

File: pkg/vsock/vsock_linux.go [hunk 1]
```diff
@@ -39,6 +53,8 @@ func Dial(cid, port uint32) (Conn, error) {
 			if errno, ok := err.(syscall.Errno); ok && errno == syscall.EINTR {
 				continue
 			}
+			// Trying not to leak fd here
+			closeFD(fd)
```
Comment (rn) [inline pkg/vsock/vsock_linux.go]: Hey, thanks for reporting this and providing a patch. 

I'd be happy to merge bar this minor nit. This ignores the return value, which is fine since we want the error from the `Connect()` call. However this may trip some linters and the canonical way would be to write:
```
_ := closeFD(fd)
```

Comment (xelez) [reply pkg/vsock/vsock_linux.go]: Thanks for the review! Good point.

`:=` gives me an error:
```
# github.com/linuxkit/virtsock/pkg/vsock
pkg/vsock/vsock_linux.go:57:6: no new variables on left side of :=
```

So I fixed it with just `_ = `.

**Review by rn — APPROVED** [review]
Great, thanks for the fix.
